# Generated by Django 4.2.4 on 2023-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='Django_prodjango/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
